fluidPage(
    br(),
    fluidRow(
        column(width = 3,
               box(width = 12,
                   pickerInput(
                       inputId = "specie",
                       label = "1. Select species",
                       choices = list("Human" = "Hs",
                                      "Mouse" = "Mm",
                                      "Rat" = "Rn",
                                      "Arabidopsis" = "At"),
                       options = list(title = "species"),
                       selected = NULL
                   ), 
                   uiOutput("matrixDeseq"),
                   sidebarMenu(fluidRow(
                       column(width=1,
                              menuItem(uiOutput("circleinfoDO")),
                              menuItem(uiOutput("tooltipDO"))
                              ),
                       column(width=12,
                              menuItem(uiOutput("deseqFile"))
                              ) ) ),
                   uiOutput("design"),
                   sidebarMenu(fluidRow(
                       column(width=1,
                              menuItem(uiOutput("circleinfoCM")),
                              menuItem(uiOutput("tooltipCM"))
                              ),
                       column(width=12,
                              menuItem(uiOutput("countFile")),
                       
                              menuItem(uiOutput("sampleFile")))
                       )),
                   uiOutput("testVariable"),
                   uiOutput("designMatrix")
                   ) # fin box
               ),
        column(width = 8,
                    box(width=12,
                        status = "info",
                        title = h1(strong("Welcome to Go DESeq DEVEA 2022!") ),
                        h3("Data requirements:"),
                        p(HTML(paste0("Option 1. ", '<B>Counting matrix (CM + SI) mode:</B>')), HTML(paste0("consists of a ", '<B>counting matrix (CM)</B>')),
                          "where columns are samples and rows are features,
                          containing the raw number of transcripts read counts. 
                          This input mode is associated with an extra file ", HTML(paste0("gathering the ", '<B>sample information (SI),</B>')),  
                          "as a data frame containing metadata about each sample. It should include any relevant 
                          experimental factors (e.g. treatment/control, sex, cell type, tissue, etc.) and it has 
                          to contain in the first column the sample identifier, which will be used by default to 
                          label the samples in the different visualizations.", 
                          br(),
                          br(),
                          HTML(paste0("Option 2. ", '<B>DESeq object (DO) mode: </B>')), HTML(paste0("based on a ", '<B>DeseqDataSet object (DO)</B>')), 
                          " generated by the DESeq( ) function from ",
                          a("DESeq2", href="https://bioconductor.org/packages/release/bioc/vignettes/DESeq2/inst/doc/DESeq2.html"),
                          "library and compress as a RDS file. This object must contain the
                          CountData field as the data matrix of counts, the ColData field 
                          with the sample information, where the first column in the CountData 
                          and the first row in the ColData are equal, and a formula which specifies
                          the design of the experiment to perform the DEA on it. "),
              br(),
              p("Note that demo data is also available here to test the performance.
                For further details on how to use DEVEA,
                please take advantage of every symbol of info" , icon("info-circle"), "that you might find,
                see our ",
                a("paper", href = "https://f1000research.com/articles/11-711"), 
                "and a detailed walkthrough in the 'Tutorial' section. Source code at ",
                a("GitHub.", href = "https://github.com/MiriamRiquelmeP/DEVEA"),
                "For feedbacks, please contact us (information available in the 'About' section).") ),
    ) ),
    fluidRow(
        column(width = 6,
               # box(width = 12, 
               #     title = "Sample table",
                   DTOutput("coldataTable")
               #)
        ),
        column(width = 6,
               # box(width = NULL,
               #     title = "Expression matrix (first 10 rows)",
                   #div(style = 'overflow-x: scroll',
               DT::dataTableOutput("expressionTable")#)
                   #)
        )
    )
)
